### ISSUE TITLE
Determine if/how duplicate tags should be handled when resolving a context.

### ISSUE THREAD

**Issue by tobz** [DataDog/saluki#161]
## Context

Currently, we do not handle the possibility of [duplicate tags when hashing a context](https://github.com/DataDog/saluki/blob/5bcb3dadc113d0e6a46e4b6a6c0023518f69bdd3/lib/saluki-context/src/lib.rs#L693-L698), and more generally, do nothing to handle duplicate tags at all.

We should check the implementation of the context resolver in the Datadog Agent to determine if ignoring duplicate tags is OK or if we need to do something with them, and if so, what we should be doing.

Essentially, we want to be at parity with the Datadog Agent when it comes to duplicated tags in a metric.

**Comment by CouldBeFree** [comment]
FMPOV there is no point in saving duplicate hash, as far as in this case, we will run into the hash collision.
I think that we should check if there is already a created hash with the following name, if such name already exists we should ignore it and throw some warning.
@tobz what do you think?

**Comment by tobz** [comment]
This was fixed back in #209.
